config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  resources :patients
  resources :doctors
  root "patients#index"
  get '/check', :controller=>'patients', :action=>'checkprice'
  post '/validate', :controller=>'patients', :action=>'cost'
  get '/email', :controller=>'patients', :action=>'contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_doctor! 
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    
    #Code for searching Patient
    @q = Patient.ransack(params[:q])
    @patients = @q.result(distinct: true)
    
    #Code for rendering Patient data as pdf
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PatientPdf.new(@patient)
        send_data pdf.render, filename: 'patients.pdf',type: 'application/pdf',disposition: "inline"

      end
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end
  
  #Code for Custom Gem, taking in user input and displaying results
  def cost
     @input1 = params[:search_string]
     @result = Calcgem.runcheck(@input1.to_i)
  end
  
  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :age, :date_of_birth, :address, :phone_no, :condition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material\Icons" rel="stylesheet">
    <title>CadProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav>
      <div class="nav-wrapper">
        
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <%= render 'devise/menu/registration_items' %>
          <%= render 'devise/menu/login_items' %>
          <% unless !doctor_signed_in? %>
          <li><a href="patients">Patients</a></li>
          <li><a href="check">Check Price</a></li>
          
          <%end%>
        </ul>
      </div>
    </nav>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :patient_name %>
  </div>
  
   <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age, id: :patient_age %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth, id: :patient_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :phone_no %>
    <%= form.number_field :phone_no, id: :patient_phone_no %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, id: :patient_condition %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/checkprice.html.erb
<!--Code to input age-->
<h1>Enter an Age to check Price</h1>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>
<% end %>

app/views/patients/cost.html.erb
<!--Code to display result-->
<h1>Enter an Age to check Price</h1>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>
<% end %>

<%= @result %>
<hr>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<!--Code for searching by condition and sorting based on age-->
<%= search_form_for @q do |f| %>
  <div class="field">
    <%= f.label :condition_cont, "Patients with Condition" %>
    <%= f.text_field :condition_cont %>
    <%= sort_link(@q, :age, 'Sort by Age') %>
  </div>
  
  <div class="actions"><%= f.submit "Search" %></div>
  
<% end %>
<!--Code to display Patient data-->
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Date of birth</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>Condition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone_no %></td>
        <td><%= patient.condition %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--Code to create new Patient record and view records as pdf-->
<%= link_to 'New Patient', new_patient_path %>
<%= link_to 'View as PDF', patients_path(format: "pdf") %>

<!--Code to display Patient conditions on pie chart-->
<%= pie_chart Patient.group(:condition).count %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @patient.phone_no %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @patient.condition %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>